# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
Tensor = torch.rand(7,7)
Tensor

tensor([[0.8919, 0.1887, 0.3581, 0.4671, 0.1948, 0.0034, 0.9103],
        [0.9806, 0.7755, 0.3441, 0.2475, 0.2819, 0.6715, 0.5589],
        [0.6282, 0.1810, 0.5000, 0.2648, 0.3243, 0.8079, 0.3674],
        [0.0722, 0.0141, 0.7461, 0.2926, 0.0111, 0.4491, 0.3318],
        [0.5503, 0.9036, 0.1392, 0.1678, 0.4126, 0.9771, 0.2714],
        [0.4102, 0.8288, 0.9039, 0.1258, 0.9637, 0.6762, 0.1081],
        [0.9039, 0.1636, 0.1041, 0.4830, 0.0256, 0.1466, 0.7453]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [8]:
# Create another random tensor
TENSOR1 = torch.rand(1,7).T
tensor = torch.rand(1,1)
TENSOR = torch.matmul(TENSOR1, tensor)
# Perform matrix multiplication
TENSOR, TENSOR.shape


(tensor([[0.0171],
         [0.0583],
         [0.0222],
         [0.0378],
         [0.0456],
         [0.0019],
         [0.0519]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [22]:
import torch
# Set manual seed
RANDOM_SEED = 0
# Create two random tensors
torch.manual_seed(RANDOM_SEED)
TENSOR1 = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
TENSOR2 = torch.rand(1,7).T

# Matrix multiply tensors
TENSOR = torch.matmul(TENSOR1, TENSOR2)
TENSOR, TENSOR.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
# normal way of setting random seed
import torch
RANDOM_SEEDS = 42




### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
# Set random seed
import torch
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

# Check for access to GPU
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
device
# Create two random tensors on GPU
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)
tensor_A_to_gpu = tensor_A.to(device)
tensor_B_to_gpu = tensor_B.to(device)
print(tensor_A, tensor_A_to_gpu.device)
print(tensor_B, tensor_B_to_gpu.device)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) cuda:0
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]) cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [18]:
# Perform matmul on tensor_A and tensor_B
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(3,2)
tensor_A_to_gpu = tensor_A.to(device)
tensor_B_to_gpu = tensor_B.to(device)
tensor = torch.matmul(tensor_A_to_gpu, tensor_B_to_gpu)
tensor, tensor.shape

(tensor([[1.4650, 0.8633],
         [1.0159, 0.5133]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [21]:
# Find max
torch.max(tensor)
# Find min
torch.min(tensor)
print(torch.max(tensor), torch.min(tensor))

tensor(1.4650, device='cuda:0') tensor(0.5133, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [24]:
# Find arg max
torch.argmin(tensor)

# Find arg min
torch.argmax(tensor)

print(torch.argmin(tensor), torch.argmax(tensor))

tensor(3, device='cuda:0') tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
