# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch
# Create random tensor
x = torch.rand(7,7)
x

tensor([[0.9955, 0.8087, 0.0115, 0.0539, 0.0718, 0.7887, 0.0754],
        [0.1110, 0.1691, 0.9193, 0.2800, 0.9930, 0.8514, 0.7065],
        [0.9628, 0.2859, 0.2328, 0.2561, 0.1379, 0.6191, 0.2268],
        [0.8415, 0.0386, 0.7781, 0.2600, 0.0524, 0.2759, 0.4866],
        [0.0420, 0.3219, 0.4937, 0.4204, 0.4818, 0.7151, 0.1863],
        [0.1509, 0.2813, 0.9048, 0.7935, 0.7524, 0.6011, 0.9237],
        [0.2335, 0.9455, 0.6674, 0.1668, 0.3695, 0.2898, 0.3562]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
x = torch.rand(1,7)
y = torch.rand(1,7).T
# Perform matrix multiplication
Tensor = torch.matmul(x,y)
Tensor, Tensor.shape

(tensor([[2.2234]]), torch.Size([1, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
import torch
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
# Create two random tensors
x = torch.rand(7,7)
y = torch.rand(1,7).T
# Matrix multiply tensors
TENSOR = torch.matmul(x,y)
TENSOR, TENSOR.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [20]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
import torch
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
# Check for access to GPU
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
x = torch.rand(2,3)
y = torch.rand(2,3)
x_cuda = x.to(device)
y_cuda = y.to(device)
print(x_cuda)
print(y_cuda)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
x = torch.rand(2,3)
y = torch.rand(3,2)
x_cuda = x.to(device)
y_cuda = y.to(device)
TENSOR = torch.matmul(x_cuda, y_cuda)
TENSOR, TENSOR.shape

(tensor([[0.7496, 0.9922],
         [0.5006, 0.9982]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [11]:
# Find max
torch.max(TENSOR)
# Find min
torch.min(TENSOR)
print(torch.max(TENSOR), torch.min(TENSOR))

tensor(0.9982, device='cuda:0') tensor(0.5006, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
X = torch.argmax(TENSOR)

# Find arg min
Y = torch.argmin(TENSOR)
print(f"argmax: {X}, argmin: {Y}")

argmax: 3, argmin: 2



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
import torch
RANDOM_SEED = 7

# Create random tensor
torch.manual_seed(RANDOM_SEED)
X = torch.rand(1,1,1,10)

# Remove single dimensions
torch.manual_seed(RANDOM_SEED)
X_Squeeze = torch.squeeze(X)

# Print out tensors and their shapes
print(f"{X, X.shape}, {X_Squeeze, X_Squeeze.shape}")

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10])), (tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
